EW refs #44948: Public engagements ct
ytgov/yukon-ca pull request #37
Opened 2023-02-22 12:19 UTC by viktoriia-sobutska

- Created vocabulary Engagement Categories with additional fields: Meta tags and Image(media:Image).
- Created migration file for Engagement Categories terms migration.
- Created fields for Public engagements content type.
- Added data into hook_migrate_prepare_row.
- Added conditions into hook_migrate_prepare_row, added yukon_migrate_set_pathauto_check_value() function.
- Changed path/pathauto value in nodes and taxonomy migrations.
- Created file for Public Engagements Nodes migration

2023-02-28 16:02 UTC, alt-ew requested changes

2023-02-28 16:02 UTC, alt-ew commented on docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_engagement_translation.yml
> +    slash: '/'
```suggestion
```

2023-02-28 16:02 UTC, alt-ew commented on docroot/modules/custom/yukon_migrate/migrations/taxonomies/yukon_migrate_engagement_categories.yml
> +        migration: yukon_migrate_images
Let's add this migration to the dependency

2023-03-01 09:28 UTC, viktoriia-sobutska commented on docroot/modules/custom/yukon_migrate/migrations/nodes/yukon_migrate_engagement_translation.yml
> +      - yukon_migrate_department
```suggestion
    - yukon_migrate_engagement_categories
    - yukon_migrate_teams
    - yukon_migrate_department
```

2023-03-01 09:40 UTC, alt-ew approved these changes

2023-03-01 09:47 UTC, merged