EW refs #45641: Preprocess function
ytgov/yukon-ca pull request #75
Opened 2023-03-09 12:36 UTC by viktoriia-sobutska

- Created documents page template.
- Rewrite general style for label.
- Get in preprocess function all data from file entity

2023-03-09 12:37 UTC, viktoriia-sobutska commented on docroot/themes/custom/yukonca_glider/src/sass/pages/_documents.page.scss
> +}
```suggestion
}

```

2023-03-09 16:39 UTC, alt-ew requested changes

2023-03-09 16:39 UTC, alt-ew commented on docroot/themes/custom/yukonca_glider/yukonca_glider.theme
> +  if (!$node->get('field_document_upload')->isEmpty()) {
Why you are so sure that node has this field?

2023-03-09 16:39 UTC, alt-ew commented on docroot/themes/custom/yukonca_glider/yukonca_glider.theme
> +    $file = \Drupal::entityTypeManager()->getStorage('file')->load($media_file->get('field_media_file')->getString());
Same here.
Also how can you be sure that entity exists?

2023-03-10 18:57 UTC, alt-ew approved these changes

2023-03-10 18:57 UTC, merged